version: 2
jobs:
  build:
    working_directory: ~/deps

    docker:
      - image: docker:18.06.0-ce-git

    environment:
      VERSION: "3.4.10"
      BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
      VCS_REF: ${CIRCLE_SHA1:0:7}
      TAG: ${VERSION}-alpine
      TAG_SHORT: 3.4-alpine
      BATS_VER: "0.4.0"  

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce

      # - run:
      #     name: set TAG vars
      #     command: |
      #       export TAG=${VERSION}-alpine
      #       export TAG_MINOR=${VERSION%.*}-alpine
      #       export TAG_MAJOR=${VERSION%%.*}-alpine           

      - run:
          name: install dependencies - lib
          command: |
            apk --no-cache add \
              bash \
              curl \
              curl-dev \
              make \
              python3 
            
            pip3 install --upgrade pip
            pip3 install docker-compose==1.22.0

      - run:
          name: install dependencies - bats
          command: |
            dir=${CIRCLE_WORKING_DIRECTORY}
            mkdir -p ${dir}

            if [[ ! -e ${dir}/bats_v${BATS_VER}.tar.gz ]]; then 
              curl -sSL -o ${dir}/bats_v${BATS_VER}.tar.gz https://github.com/sstephenson/bats/archive/v${BATS_VER}.tar.gz
            fi
            
            tar -xf ${dir}/bats_v${BATS_VER}.tar.gz
            bats-${BATS_VER}/install.sh /usr/local

      - run:
          name: docker client and remote info
          command: |
            docker version
            docker info

      - run:
          name: docker image build
          command: make all
          working_directory: "3.4"

      - run:
          name: test
          command: |
            docker inspect robnightingale/zookeeper:${TAG}
            make test
          working_directory: "3.4"

      - run:
          name: docker image push
          command: |
            TAG_MINOR=${VERSION%.*}-alpine
            TAG_MAJOR=${VERSION%%.*}-alpine 

            if [ "${CIRCLE_BRANCH}" == "3.0" ]; then
              docker image tag robnightingale/zookeeper:${TAG} robnightingale/zookeeper
              docker image tag robnightingale/zookeeper:${TAG} robnightingale/zookeeper:${TAG_MINOR}
              docker image tag robnightingale/zookeeper:${TAG} robnightingale/zookeeper:${TAG_MAJOR}
            #  docker login -u $DOCKER_USER -p $DOCKER_PASS
            #  docker image push robnightingale/zookeeper:${TAG}
            #  docker image push robnightingale/zookeeper:${TAG_MINOR}
            #  docker image push robnightingale/zookeeper:${TAG_MAJOR}
            #  docker image push robnightingale/zookeeper:latest
            #  docker logout
            # curl -X POST 'https://hooks.microbadger.com/images/smizy/zookeeper/qxHGCqKcI_P_sS8Ek0I8Ck9wEl8='
            fi
          working_directory: "3.4"
